# Generated by Django 2.2.24 on 2021-06-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='user',
            new_name='student',
        ),
    ]
