# Generated by Django 2.2.24 on 2021-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210619_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='class',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
